plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.f5'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2024.0.0") // 최신버전 확인 후 적용
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'  // WebFlux 기반으로 작동
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway' // Spring Cloud Gateway
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0' // Jakarta Servlet 의존성 추가

    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'  // JWT API 모듈
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5' // JWT 구현 모듈
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5' // Jackson을 사용한 JWT 처리

    implementation 'javax.annotation:javax.annotation-api:1.3.2'
}

tasks.named('test') {
    useJUnitPlatform()
}
